### ISSUE TITLE
ERROR: media-libs/libgmpris-2.2.1  user.eclass could not be found by inherit

### ISSUE THREAD

**Issue by Kajanos** [zhjie/zhjie_gentoo_repo#1]
Reading category 108|182 ( 59): media-libs... * ERROR: media-libs/libgmpris-2.2.1::zhjie-repo failed (depend phase):
 *   user.eclass could not be found by inherit()
 * 
 * Call stack:
 *                ebuild.sh, line 628:  Called source '/var/db/repos/zhjie-repo/media-libs/libgmpris/libgmpris-2.2.1.ebuild'
 *   libgmpris-2.2.1.ebuild, line   7:  Called inherit 'unpacker' 'user'
 *                ebuild.sh, line 273:  Called die
 * The specific snippet of code:
 *              [[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=media-libs/libgmpris-2.2.1::zhjie-repo'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/libgmpris-2.2.1::zhjie-repo'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/libgmpris-2.2.1'

ebuild failed with status 1

**Comment by zhjie** [comment]
fixed, thanks
