### ISSUE TITLE
media-sound/RoonServer-2.0.25 checksum failure

### ISSUE THREAD

**Issue by Kajanos** [zhjie/zhjie_gentoo_repo#2]
110350K .......... .......... .......... .......... ......... 100% 86,5M=1,4s

2023-11-16 11:34:31 (75,3 MB/s) - ‘/var/cache/distfiles/RoonServer-2.0.25.tar.bz2.__download__’ saved [113049594/113049594]

!!! Fetched file: RoonServer-2.0.25.tar.bz2 VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      113049594
!!! Expected: 112992223
Refetching... File renamed to '/var/cache/distfiles/RoonServer-2.0.25.tar.bz2._checksum_failure_._o0ct4q0'

**Comment by zhjie** [comment]
Thanks, I try to generate a revision 2.0.25-r1 based on http://download.roonlabs.com/builds/RoonServer_linuxx64.tar.bz2.

**Comment by Kajanos** [comment]
Thank you looks fine RoonServer-2.0.25-r1
